// Standalone entry: serves the embedded single-file UI + API from one process
// and opens the browser on launch. Built into LocalLlama.exe via `bun run package`.
import { spawn } from "node:child_process";

import { createApp } from "./app";
import { BenchmarkManager } from "./benchmark";
import { createBenchmarkStore } from "./benchmarkStore";
import { DownloadManager } from "./downloadManager";
import { RuntimeManager } from "./runtime";
// Embedded at compile time by `bun build --compile`. Generated by
// scripts/inline-frontend.ts (run `bun run build:standalone` first).
import appHtml from "../dist/standalone.html.txt" with { type: "text" };

const port = Number(process.env.LOCALLLAMA_PORT ?? 4187);
const host = process.env.LOCALLLAMA_HOST ?? "127.0.0.1";

const runtime = new RuntimeManager();
const benchmarkStore = createBenchmarkStore();
const benchmark = new BenchmarkManager(benchmarkStore);
const downloads = new DownloadManager();

let shuttingDown = false;

async function shutdown(signal: NodeJS.Signals): Promise<void> {
  if (shuttingDown) {
    return;
  }
  shuttingDown = true;
  console.log(`\nReceived ${signal}, stopping child processes...`);
  try {
    await Promise.allSettled([runtime.stop(), benchmark.stop(), downloads.dispose()]);
  } finally {
    process.exit(0);
  }
}

process.on("SIGINT", () => void shutdown("SIGINT"));
process.on("SIGTERM", () => void shutdown("SIGTERM"));

function openBrowser(url: string): void {
  if (process.env.LOCALLLAMA_NO_OPEN) {
    return;
  }
  try {
    if (process.platform === "win32") {
      // `start` is a cmd builtin; the empty "" is its window-title argument.
      spawn("cmd", ["/c", "start", "", url], { stdio: "ignore", detached: true, windowsHide: true }).unref();
    } else if (process.platform === "darwin") {
      spawn("open", [url], { stdio: "ignore", detached: true }).unref();
    } else {
      spawn("xdg-open", [url], { stdio: "ignore", detached: true }).unref();
    }
  } catch {
    // Best-effort; the URL is also printed below.
  }
}

function listen(candidatePort: number, retries = 0): void {
  const server = createApp({ runtime, benchmarkStore, benchmark, downloads, appHtml });
  server.once("error", (error: NodeJS.ErrnoException) => {
    if (error.code === "EADDRINUSE" && !process.env.LOCALLLAMA_PORT && retries < 10) {
      listen(candidatePort + 1, retries + 1);
      return;
    }
    console.error(error.message);
    process.exit(1);
  });
  server.listen(candidatePort, host, () => {
    const url = `http://${host}:${candidatePort}`;
    console.log(`LocalLlama is running at ${url}`);
    console.log("Close this window (or press Ctrl+C) to stop the server.");
    openBrowser(url);
  });
}

listen(port);
